### ISSUE TITLE
Automatic build for different platforms

### ISSUE THREAD

**Issue by AndreKoepke** [AndreKoepke/home-system#118]
Locally, it works like a charm to build with quarkus for different platforms. But it fails in Github Actions.

```yaml
      - name: Build and publish for raspberry
        run: ./gradlew build -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true
        env:
          QUARKUS_CONTAINER_IMAGE_GROUP: akop
          QUARKUS_CONTAINER_IMAGE_NAME: home-system
          QUARKUS_CONTAINER_IMAGE_TAG: latest
          QUARKUS_CONTAINER_IMAGE_USERNAME: '${{ secrets.DOCKER_USER }}'
          QUARKUS_CONTAINER_IMAGE_PASSWORD: '${{ secrets.DOCKER_PASS }}'
          QUARKUS_DOCKER_BUILDX_PLATFORM: linux/arm/v7
          REPO_USERNAME: '${{ secrets.REPO_GITHUB_NAME }}'
          REPO_TOKEN: '${{ secrets.REPO_GITHUB_TOKEN }}'
```

Perhaps it is better, to build java and export the outcome to pure docker-builder.  
Then it is possible to use the dockerfiles (under `src/java/main/resources/docker`)
